### ISSUE TITLE
Add warnings about keys and instructions about config overrides

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/s3fs#2]
When configured through the UI, Amazon keys are saved in config files, which could conceivably get added to a repo that becomes public.

It would be good to:
- Add warnings on the UI interface that allows adding keys to make sure the config will not be exposed publicly
- Give an example (or link to one in the Wiki) on how to override config in a settings file that is in `.gitignore` so it won't be committed to a repo.

**Comment by herbdool** [comment]
Perhaps move the S3 key from the config file entirely and require users to set it in the settings file. Or you could also encrypt the S3 keys using Encrypt module if keeping the option to store it in the config file.

**Comment by keiserjb** [comment]
I think I'll just require the config is settings.php.  I don't want anybody else to have this problem because it is easy to do without realizing.

**Comment by keiserjb** [comment]
I removed the ability to save the AWS keys in the UI so it does not get saved to the config files.  I am also looking at the [Key Module](https://www.drupal.org/project/key).

@herbdool looking at what you did with Encrypt and Plugin Manager.

**Comment by keiserjb** [comment]
After a flurry of activity I think this issue and a lot of other problems are solved.
