### ISSUE TITLE
Not using the selected keys when working with the Key module

### ISSUE THREAD

**Issue by AleMadLei** [backdrop-contrib/s3fs#8]
I created two keys using the key module, one for the access key and another for the secret key.

The module doesn't work because it is trying to load a very specific and hardcoded key name.

**Comment by AleMadLei** [comment]
This PR addresses the problem https://github.com/backdrop-contrib/s3fs/pull/7

**Comment by keiserjb** [comment]
Yes, thank you.  I've known this wasn't working correctly but I didn't make another release of the module.

**Comment by keiserjb** [comment]
I committed the pr.
